from flask import Blueprint, request, jsonify, render_template
from flask_jwt_extended import jwt_required, get_jwt_identity
from models import Tutor, TutorModule
from database.db import db
from database.client import SQLiteDatabaseClient
import json
from datetime import datetime

tutor_bp = Blueprint('tutor', __name__)

# --- INITIALIZE DATABASE CLIENT ---
all_models = {'Tutor': Tutor, 'Module': TutorModule}
db_client = SQLiteDatabaseClient(db.session, all_models)


@tutor_bp.route('/create', methods=['POST'])
#@jwt_required()
def create_tutor():
    """
    Create a new tutor (API).
    This endpoint is for creating a new tutor from a JSON payload.
    An ID for the new tutor is generated automatically by the database.
    """
    data = request.get_json()
    if not data or 'title' not in data:
        return jsonify({"error": "Title is required"}), 400

    # The 'id' should not be in the payload for creation, as the DB assigns it.
    if 'id' in data:
        del data['id']

    # Associate with the logged-in instructor
    data['instructor_id'] = get_jwt_identity() or 1  # Fallback for dev

    # Ensure content and settings are JSON strings
    if 'content' in data and not isinstance(data.get('content'), str):
        data['content'] = data.get('content', {})
    if 'settings' in data and not isinstance(data.get('settings'), str):
        data['settings'] = data.get('settings', {})

    # NOTE on IDs: The Tutor model uses an auto-incrementing Integer for the 'id'.
    # A UUID is not used as it is incompatible with the current database schema.
    tutor = db_client.create('Tutor', data)
    return jsonify({"message": "Tutor created successfully", "tutor": tutor.to_dict()}), 201


@tutor_bp.route('/find', methods=['POST'])
#@jwt_required()
def get_tutors():
    """Get a list of tutors by filter
    """
    data = request.get_json()
    tutors = db_client.read_all('Tutor', filters=data)
    return jsonify({"tutors": tutors.to_list(include_details=True)}), 200


@tutor_bp.route('/find/<int:tutor_id>', methods=['GET'])
#@jwt_required()
def get_tutor(tutor_id):
    """Get a specific tutor's details (API)"""
    tutor = db_client.read_by_id('Tutor', tutor_id)
    if not tutor:
        return jsonify({"error": "Tutor not found"}), 404
    return jsonify({"tutor": tutor.to_dict(include_details=True)}), 200


@tutor_bp.route('/update/<int:tutor_id>', methods=['PUT'])
#@jwt_required()
def update_tutor(tutor_id):
    """
    Update a tutor's details (API).
    If tutor_id is 0 or the tutor does not exist, a new tutor is created.
    """
    # The frontend sends tutor_id = 0 to indicate a new tutor should be created.
    # If tutor_id is a non-zero value, we first check if that tutor exists.
    existing_tutor = db_client.read_by_id('Tutor', tutor_id) if tutor_id else None

    data = request.get_json()

    if not existing_tutor:
        # --- CREATE A NEW TUTOR ---
        # This block executes if tutor_id is 0 or an ID for a non-existent tutor was provided.

        if not data or 'title' not in data:
            return jsonify({"error": "Title is required for a new tutor"}), 400

        # Associate with the logged-in instructor
        # data['instructor_id'] = get_jwt_identity() or 1  # Fallback for development
        data['instructor_id'] = 0

        # Ensure content and settings are JSON strings
        if 'content' in data and not isinstance(data.get('content'), str):
            data['content'] = data.get('content', {})
        if 'settings' in data and not isinstance(data.get('settings'), str):
            data['settings'] = data.get('settings', {})

        # NOTE on IDs: The Tutor model uses an auto-incrementing Integer for the 'id'.
        # A new, unique integer ID will be generated by the database automatically upon insertion.
        # A UUID is not used as it is incompatible with the current database schema for the Tutor ID.
        new_tutor = db_client.create('Tutor', data)
        return jsonify({
            "message": "Tutor created successfully",
            "tutor": db_client.to_dict(new_tutor)
        }), 201

    else:
        # --- UPDATE THE EXISTING TUTOR ---
        # This block executes if a valid, existing tutor_id was provided.
        data['updated_at'] = datetime.utcnow()

        # Ensure content and settings are JSON strings if they are being updated
        if 'content' in data and not isinstance(data.get('content'), str):
            data['content'] = data['content']
        if 'settings' in data and not isinstance(data.get('settings'), str):
            data['settings'] = data['settings']

        updated_tutor = db_client.update('Tutor', tutor_id, data)

        return jsonify({
            "message": "Tutor updated successfully",
            "tutor": updated_tutor.to_dict()
        }), 200


@tutor_bp.route('/delete/<int:tutor_id>', methods=['DELETE'])
@jwt_required()
def delete_tutor(tutor_id):
    """Delete a tutor (API)"""
    if db_client.delete('Tutor', tutor_id):
        return jsonify({"message": "Tutor deleted successfully"}), 200
    return jsonify({"error": "Tutor not found"}), 404


@tutor_bp.route('/publish/<int:tutor_id>', methods=['POST'])
@jwt_required()
def publish_tutor(tutor_id):
    """Publish a tutor making it available to learners (API)"""
    if db_client.update('Tutor', tutor_id, {'is_published': True}):
        return jsonify({"message": "Tutor published successfully"}), 200
    return jsonify({"error": "Tutor not found"}), 404


@tutor_bp.route('/unpublish/<int:tutor_id>', methods=['POST'])
@jwt_required()
def unpublish_tutor(tutor_id):
    """Unpublish a tutor (API)"""
    if db_client.update('Tutor', tutor_id, {'is_published': False}):
        return jsonify({"message": "Tutor unpublished successfully"}), 200
    return jsonify({"error": "Tutor not found"}), 404


@tutor_bp.route('/clone/<int:tutor_id>', methods=['POST'])
@jwt_required()
def clone_tutor(tutor_id):
    """Clone an existing tutor (API)"""
    original_tutor = db_client.read_by_id('Tutor', tutor_id)
    if not original_tutor:
        return jsonify({"error": "Tutor not found"}), 404

    clone_data = original_tutor.to_dict()
    # Modify for clone
    del clone_data['id']
    clone_data['title'] = f"{clone_data['title']} (Copy)"
    clone_data['is_published'] = False

    new_tutor = db_client.create('Tutor', clone_data)
    return jsonify({"message": "Tutor cloned successfully", "new_tutor_id": new_tutor.id}), 201


@tutor_bp.route('/<int:tutor_id>/modules', methods=['GET'])
@jwt_required()
def get_tutor_modules(tutor_id):
    """Get all modules for a specific tutor (API)

    Function: Tutor Modules
    """
    # Logic would go here
    return jsonify({"modules": []}), 200


@tutor_bp.route('/<int:tutor_id>/modules', methods=['POST'])
@jwt_required()
def create_tutor_module(tutor_id):
    """Create a new module for a tutor (API)

    Function: Module Creation
    """
    # Logic would go here
    return jsonify({"message": "Module created successfully", "module_id": 1}), 201


@tutor_bp.route('/modules/<int:module_id>', methods=['GET'])
@jwt_required()
def get_module(module_id):
    """Get a specific module's details (API)

    Function: Module Details
    """
    # Logic would go here
    return jsonify({"module": {}}), 200


@tutor_bp.route('/modules/<int:module_id>', methods=['PUT'])
@jwt_required()
def update_module(module_id):
    """Update a module's details (API)

    Function: Module Update
    """
    # Logic would go here
    return jsonify({"message": "Module updated successfully"}), 200


@tutor_bp.route('/modules/<int:module_id>', methods=['DELETE'])
@jwt_required()
def delete_module(module_id):
    """Delete a module (API)

    Function: Module Deletion
    """
    # Logic would go here
    return jsonify({"message": "Module deleted successfully"}), 200


@tutor_bp.route('/modules/reorder', methods=['POST'])
@jwt_required()
def reorder_modules():
    """Reorder modules within a tutor (API)

    Function: Module Reordering
    """
    # Logic would go here
    return jsonify({"message": "Modules reordered successfully"}), 200


@tutor_bp.route('/import', methods=['POST'])
@jwt_required()
def import_tutor():
    """Import a tutor from a file (API)

    Function: Tutor Import
    """
    # Logic would go here
    return jsonify({"message": "Tutor imported successfully", "tutor_id": 3}), 201


# Web UI Endpoints

@tutor_bp.route('/create', methods=['GET'])
def create_tutor_page():
    """Render the tutor creation page (Web UI)

    Function: Tutor Creation Page
    """
    return render_template('tutor/create.html')


@tutor_bp.route('/edit/<int:tutor_id>', methods=['GET'])
def edit_tutor_page(tutor_id):
    """Render the tutor editing page (Web UI)

    Function: Tutor Editing Page
    """
    return render_template('tutor/edit.html', tutor_id=tutor_id)


@tutor_bp.route('/view/<int:tutor_id>', methods=['GET'])
def view_tutor_page(tutor_id):
    """Render the tutor view page (Web UI)

    Function: Tutor View Page
    """
    return render_template('tutor/view.html', tutor_id=tutor_id)


@tutor_bp.route('/modules/create/<int:tutor_id>', methods=['GET'])
def create_module_page(tutor_id):
    """Render the module creation page (Web UI)

    Function: Module Creation Page
    """
    return render_template('tutor/module_create.html', tutor_id=tutor_id)


@tutor_bp.route('/modules/edit/<int:module_id>', methods=['GET'])
def edit_module_page(module_id):
    """Render the module editing page (Web UI)

    Function: Module Editing Page
    """
    return render_template('tutor/module_edit.html', module_id=module_id)

